/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.security.authorization.entity.creditorder;

import lombok.Getter;
import lombok.Setter;

@Getter @Setter
public class CreditOrderAutoCompleteImpl implements CreditOrderAutoComplete {

	private java.util.UUID id;
	
	private String orderUserName;
	
	public CreditOrderAutoCompleteImpl() {
		// Contructor for reflexion, injection, Jackson, QueryDSL, etc proposal.
	}

}
