/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.security.authorization.entity.tenant;



public interface TenantAutoComplete {

	java.util.UUID getId();
	
	String getName();
	
	void setId(java.util.UUID id);
	
	void setName(String name);

}
