/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.security.authorization.entity.tenantopcount;

import com.querydsl.core.types.Predicate;

public interface TenantOpCountListFilterPredicate {
	
	Predicate mountAndGetPredicate(TenantOpCountListFilter tenantOpCountListFilter);

}

