/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.security.authorization;


public enum PaymentMethod {
	CASH,
	BANK_ACCOUNT,
	CREDIT_CARD,
	BANK_SLIP,
	PIC_PAY;
}

