/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.security.authorization.entity.tenantopcount;

import br.com.kerubin.api.security.authorization.entity.tenant.TenantEntity;
import br.com.kerubin.api.security.authorization.entity.tenant.TenantLookupResult;
import org.junit.runner.RunWith;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import javax.inject.Inject;
import br.com.kerubin.api.security.authorization.entity.tenant.TenantRepository;
import org.springframework.boot.test.mock.mockito.MockBean;
import br.com.kerubin.api.messaging.core.DomainEntityEventsPublisher;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.times;
import static org.mockito.ArgumentMatchers.any;
import java.util.List;
import java.util.ArrayList;
import java.util.stream.Collectors;
import java.util.Collection;
import br.com.kerubin.api.security.authorization.entity.tenant.TenantAutoComplete;

import org.junit.Test;
import static org.assertj.core.api.Assertions.assertThat;
import br.com.kerubin.api.security.authorization.SecurityAuthorizationBaseEntityTest;


@RunWith(SpringRunner.class)
public class TenantOpCountServiceTest extends SecurityAuthorizationBaseEntityTest {
	
	private static final String[] IGNORED_FIELDS = { "id" };
	
	@TestConfiguration
	static class TenantOpCountServiceTestConfig {
		
		@Bean
		public TenantOpCountListFilterPredicate tenantOpCountListFilterPredicate() {
			return new TenantOpCountListFilterPredicateImpl();
		}
		
		@Bean
		public TenantOpCountService tenantOpCountService() {
			return new TenantOpCountServiceImpl();
		}
		
		@Bean
		public TenantOpCountDTOConverter tenantOpCountDTOConverter() {
			return new TenantOpCountDTOConverter();
		}
		
	}
	
	
	@Inject
	protected TenantOpCountService tenantOpCountService;
	
	@Inject
	protected TenantOpCountDTOConverter tenantOpCountDTOConverter;
	
	@Inject
	protected TenantOpCountRepository tenantOpCountRepository;
	
	@Inject
	protected TenantRepository tenantRepository;
	
	@MockBean
	protected DomainEntityEventsPublisher publisher;
	
	// BEGIN CREATE TESTS
	
	@Test
	public void testCreateWithAllFields() throws Exception {
		TenantOpCount tenantOpCount = new TenantOpCount();
		
		tenantOpCount.setId(java.util.UUID.randomUUID());
		tenantOpCount.setDescription(generateRandomString(255));
		
		TenantEntity tenantEntityParam = newTenantEntity();
		TenantLookupResult tenant = newTenantLookupResult(tenantEntityParam);
		tenantOpCount.setTenant(tenant);
		
		tenantOpCount.setYearOp(6914556705628527623L);
		tenantOpCount.setMonthOp(-9201895124280886344L);
		tenantOpCount.setDayOp(9207622296236495164L);
		tenantOpCount.setHourOp(8761034417586932746L);
		tenantOpCount.setCountGet(-1118481177676487285L);
		tenantOpCount.setCountPost(-447385516208145720L);
		tenantOpCount.setCountPut(-7485583168442730060L);
		tenantOpCount.setCountDelete(-567722327220322290L);
		tenantOpCount.setCountList(-7017539612584200228L);
		tenantOpCount.setCountAutoComplete(9072629499702243724L);
		tenantOpCount.setCountOp(5253855838491019659L);
		TenantOpCountEntity tenantOpCountEntity = tenantOpCountService.create(tenantOpCountDTOConverter.convertDtoToEntity(tenantOpCount));
		em.flush();
		verify(publisher, times(0)).publish(any());
		TenantOpCount actual = tenantOpCountDTOConverter.convertEntityToDto(tenantOpCountEntity);
		
		
		assertThat(actual).isNotNull();
		assertThat(actual.getId()).isNotNull();
		assertThat(actual).isEqualToIgnoringGivenFields(tenantOpCount, IGNORED_FIELDS);
		
		
		assertThat(actual.getTenant().getId()).isNotNull();
		assertThat(actual.getTenant()).isEqualToIgnoringGivenFields(tenantOpCount.getTenant(), IGNORED_FIELDS);
		
	}
	
	@Test
	public void testCreateWithOnlyRecairedFields() throws Exception {
		TenantOpCount tenantOpCount = new TenantOpCount();
		
		tenantOpCount.setId(java.util.UUID.randomUUID());
		
		TenantEntity tenantEntityParam = newTenantEntity();
		TenantLookupResult tenant = newTenantLookupResult(tenantEntityParam);
		tenantOpCount.setTenant(tenant);
		
		tenantOpCount.setYearOp(-8614189214048374232L);
		tenantOpCount.setMonthOp(-358154264137674367L);
		tenantOpCount.setDayOp(-3624126401176677120L);
		tenantOpCount.setHourOp(-8061675174176335704L);
		tenantOpCount.setCountGet(-8254905855528703635L);
		tenantOpCount.setCountPost(-2584106585193844396L);
		tenantOpCount.setCountPut(8085860574222703973L);
		tenantOpCount.setCountDelete(7473873777331420039L);
		tenantOpCount.setCountList(8161783185875556224L);
		tenantOpCount.setCountAutoComplete(-608819226731419283L);
		tenantOpCount.setCountOp(-3546969935817072076L);
		TenantOpCountEntity tenantOpCountEntity = tenantOpCountService.create(tenantOpCountDTOConverter.convertDtoToEntity(tenantOpCount));
		em.flush();
		verify(publisher, times(0)).publish(any());
		TenantOpCount actual = tenantOpCountDTOConverter.convertEntityToDto(tenantOpCountEntity);
		
		
		assertThat(actual).isNotNull();
		assertThat(actual.getId()).isNotNull();
		assertThat(actual).isEqualToIgnoringGivenFields(tenantOpCount, IGNORED_FIELDS);
		
		
		assertThat(actual.getTenant().getId()).isNotNull();
		assertThat(actual.getTenant()).isEqualToIgnoringGivenFields(tenantOpCount.getTenant(), IGNORED_FIELDS);
	}
	// END CREATE TESTS
	
	// BEGIN READ TESTS
	
	@Test
	public void testRead1() {
		TenantOpCountEntity expectedTenantOpCountEntity = newTenantOpCountEntity();
		java.util.UUID id = expectedTenantOpCountEntity.getId();
		TenantOpCount expected = tenantOpCountDTOConverter.convertEntityToDto(expectedTenantOpCountEntity);
		TenantOpCountEntity readTenantOpCountEntity = tenantOpCountService.read(id);
		TenantOpCount actual = tenantOpCountDTOConverter.convertEntityToDto(readTenantOpCountEntity);
		
		assertThat(actual).isEqualToComparingFieldByField(expected);
		
	}
	// END READ TESTS
	
	// BEGIN UPDATE TESTS
	
	@Test
	public void testUpdateWithAllFields() throws Exception {
		TenantOpCountEntity oldTenantOpCountEntity = newTenantOpCountEntity();
		java.util.UUID id = oldTenantOpCountEntity.getId();
				
		TenantOpCount tenantOpCount = new TenantOpCount();
		tenantOpCount.setId(id);
		
		tenantOpCount.setDescription(generateRandomString(255));
		
		TenantEntity tenantEntityParam = newTenantEntity();
		TenantLookupResult tenant = newTenantLookupResult(tenantEntityParam);
		tenantOpCount.setTenant(tenant);
		
		tenantOpCount.setYearOp(-7811630200995764275L);
		tenantOpCount.setMonthOp(-8741597102945973185L);
		tenantOpCount.setDayOp(5558081063037515832L);
		tenantOpCount.setHourOp(1656807762565287212L);
		tenantOpCount.setCountGet(-4694396461898223623L);
		tenantOpCount.setCountPost(-3334037417289154657L);
		tenantOpCount.setCountPut(-610321210703816542L);
		tenantOpCount.setCountDelete(6308476699938111941L);
		tenantOpCount.setCountList(-86918041084451760L);
		tenantOpCount.setCountAutoComplete(3528737958566859982L);
		tenantOpCount.setCountOp(-5731714825345349791L);
		TenantOpCountEntity tenantOpCountEntity = tenantOpCountService.update(id, tenantOpCountDTOConverter.convertDtoToEntity(tenantOpCount));
		em.flush();
		verify(publisher, times(0)).publish(any());
		
		TenantOpCount actual = tenantOpCountDTOConverter.convertEntityToDto(tenantOpCountEntity);
		
		assertThat(actual).isNotNull();
		assertThat(actual.getId()).isNotNull();
		assertThat(actual).isEqualToIgnoringGivenFields(tenantOpCount, IGNORED_FIELDS);
		
		
		assertThat(actual.getTenant().getId()).isNotNull();
		assertThat(actual.getTenant()).isEqualToIgnoringGivenFields(tenantOpCount.getTenant(), IGNORED_FIELDS);
		
	}
	
	@Test
	public void testUpdateWithOnlyRecairedFields() throws Exception {
		TenantOpCountEntity oldTenantOpCountEntity = newTenantOpCountEntity();
		java.util.UUID id = oldTenantOpCountEntity.getId();
				
		TenantOpCount tenantOpCount = new TenantOpCount();
		tenantOpCount.setId(id);
		
		
		TenantEntity tenantEntityParam = newTenantEntity();
		TenantLookupResult tenant = newTenantLookupResult(tenantEntityParam);
		tenantOpCount.setTenant(tenant);
		
		tenantOpCount.setYearOp(7445921769186614361L);
		tenantOpCount.setMonthOp(-5187278480691912578L);
		tenantOpCount.setDayOp(-8512369359060630983L);
		tenantOpCount.setHourOp(6971279139114386670L);
		tenantOpCount.setCountGet(7779315047668503379L);
		tenantOpCount.setCountPost(-2591313554647819201L);
		tenantOpCount.setCountPut(1836804537450107842L);
		tenantOpCount.setCountDelete(7977570865534883812L);
		tenantOpCount.setCountList(-7593176083761555691L);
		tenantOpCount.setCountAutoComplete(1106391820013848877L);
		tenantOpCount.setCountOp(-4178781933744406556L);
		TenantOpCountEntity tenantOpCountEntity = tenantOpCountService.update(id, tenantOpCountDTOConverter.convertDtoToEntity(tenantOpCount));
		em.flush();
		verify(publisher, times(0)).publish(any());
		
		TenantOpCount actual = tenantOpCountDTOConverter.convertEntityToDto(tenantOpCountEntity);
		
		assertThat(actual).isNotNull();
		assertThat(actual.getId()).isNotNull();
		assertThat(actual).isEqualToIgnoringGivenFields(tenantOpCount, IGNORED_FIELDS);
		
		
		assertThat(actual.getTenant().getId()).isNotNull();
		assertThat(actual.getTenant()).isEqualToIgnoringGivenFields(tenantOpCount.getTenant(), IGNORED_FIELDS);
	}
	// END UPDATE TESTS
	
	// BEGIN DELETE TESTS
	
	@Test
	public void testDelete1() {
		TenantOpCountEntity expected = newTenantOpCountEntity();
		java.util.UUID id = expected.getId();
		
		
		expected = em.find(TenantOpCountEntity.class, id);
		assertThat(expected).isNotNull();
		tenantOpCountService.delete(id);
		verify(publisher, times(0)).publish(any());
		
		expected = em.find(TenantOpCountEntity.class, id);
		assertThat(expected).isNull();
	}
	// END DELETE TESTS
	
	// BEGIN LIST TESTS
	// END LIST TESTS
	
	// BEGIN Autocomplete TESTS
	@Test
	public void testAutoComplete() {
		// Reset lastDate field to start LocalDate fields with today in this test. 
		resetNextDate();
					
		// Generate 33 records of data for TenantOpCountEntity for this test.
		List<TenantOpCountEntity> testData = new ArrayList<>();
		final int lastRecord = 33;
		final int firstRecord = 1;
		for (int i = firstRecord; i <= lastRecord; i++) {
			testData.add(newTenantOpCountEntity());
		}
		
		// Check if 33 records of TenantOpCountEntity was generated.
		long count = tenantOpCountRepository.count();
		assertThat(count).isEqualTo(lastRecord);
		
		// Extracts 1 records of TenantOpCountEntity randomly from testData.
		final int resultSize = 1;
		List<TenantOpCountEntity> filterTestData = getRandomItemsOf(testData, resultSize);
		
		// Extracts a list with only TenantOpCountEntity.description field and configure this list as a filter.
		List<String> descriptionListFilter = filterTestData.stream().map(TenantOpCountEntity::getDescription).collect(Collectors.toList());
		// Mount the autocomplete query expression and call it.
		String query = descriptionListFilter.get(0);
		Collection<TenantOpCountAutoComplete> result = tenantOpCountService.autoComplete(query);
		
		// Assert TenantOpCountAutoComplete results.
		assertThat(result).isNotNull().hasSize(1)
		.extracting(TenantOpCountAutoComplete::getDescription)
		.containsExactlyInAnyOrderElementsOf(descriptionListFilter);
	}
	
	// END Autocomplete TESTS
	
	
	// BEGIN Relationships Autocomplete TESTS
	
	@Test
	public void testTenantOpCountTenantAutoComplete() {
		// Reset lastDate field to start LocalDate fields with today in this test. 
		resetNextDate();
					
		// Generate 3 records of data for TenantEntity for this test.
		List<TenantEntity> testData = new ArrayList<>();
		final int lastRecord = 3;
		final int firstRecord = 1;
		for (int i = firstRecord; i <= lastRecord; i++) {
			testData.add(newTenantEntity());
		}
		
		// Check if 3 records of TenantEntity was generated.
		long count = tenantRepository.count();
		assertThat(count).isEqualTo(lastRecord);
		
		// Extracts 1 records of TenantEntity randomly from testData.
		final int resultSize = 1;
		List<TenantEntity> filterTestData = getRandomItemsOf(testData, resultSize);
		
		// Extracts a list with only TenantEntity.name field and configure this list as a filter.
		List<String> nameListFilter = filterTestData.stream().map(TenantEntity::getName).collect(Collectors.toList());
		String query = nameListFilter.get(0);
		
		Collection<TenantAutoComplete> result = tenantOpCountService.tenantTenantAutoComplete(query);
		
		assertThat(result).isNotNull().hasSize(1)
		.extracting(TenantAutoComplete::getName)
		.containsExactlyInAnyOrderElementsOf(nameListFilter);
	}
	
	// END Relationships Autocomplete TESTS
	
	// BEGIN tests for Sum Fields
	// END tests for Sum Fields
	
	// BEGIN tests for Sum Fields
	// END tests for Sum Fields
	
	// BEGIN TESTS DEPENDENCIES
	
	
	protected TenantOpCountEntity newTenantOpCountEntity() {
		TenantOpCountEntity tenantOpCountEntity = new TenantOpCountEntity();
		
		tenantOpCountEntity.setDescription(generateRandomString(255));
		tenantOpCountEntity.setTenant(newTenantEntity());
		tenantOpCountEntity.setYearOp(-8265079646554175996L);
		tenantOpCountEntity.setMonthOp(2228359384364140908L);
		tenantOpCountEntity.setDayOp(8714104507666325892L);
		tenantOpCountEntity.setHourOp(-3629736069032874090L);
		tenantOpCountEntity.setCountGet(-5343783029619743240L);
		tenantOpCountEntity.setCountPost(5992427572051847442L);
		tenantOpCountEntity.setCountPut(6222478294817449608L);
		tenantOpCountEntity.setCountDelete(4005289211113358166L);
		tenantOpCountEntity.setCountList(-5485158811379251574L);
		tenantOpCountEntity.setCountAutoComplete(-8851020149132551718L);
		tenantOpCountEntity.setCountOp(5275824360970924959L);
		
		tenantOpCountEntity = em.persistAndFlush(tenantOpCountEntity);
		return tenantOpCountEntity;
	}
	
	
	protected TenantOpCountLookupResult newTenantOpCountLookupResult(TenantOpCountEntity tenantOpCountEntity) {
		TenantOpCountLookupResult tenantOpCount = new TenantOpCountLookupResult();
		
		tenantOpCount.setId(tenantOpCountEntity.getId());
		tenantOpCount.setDescription(tenantOpCountEntity.getDescription());
		
		return tenantOpCount;
	}
	
	
	protected TenantEntity newTenantEntity() {
		TenantEntity tenantEntity = new TenantEntity();
		
		tenantEntity.setName(generateRandomString(255));
		tenantEntity.setMaxUsers(-9223329563614983949L);
		tenantEntity.setBalance(new java.math.BigDecimal("31569.12126"));
		tenantEntity.setActive(false);
		
		tenantEntity = em.persistAndFlush(tenantEntity);
		return tenantEntity;
	}
	
	
	protected TenantLookupResult newTenantLookupResult(TenantEntity tenantEntity) {
		TenantLookupResult tenant = new TenantLookupResult();
		
		tenant.setId(tenantEntity.getId());
		tenant.setName(tenantEntity.getName());
		
		return tenant;
	}
	// END TESTS DEPENDENCIES

}
