spring:
    rabbitmq:
        port: ${RABBITMQ_PORT:5672}
        username: ${RABBITMQ_USERNAME:admin}
        password: ${RABBITMQ_PASSWORD:admin}
#        host: ${RABBITMQ_HOST:localhost}
        host: ${RABBITMQ_HOST:lobokoch-virtualbox}
# --spring.rabbitmq.host=localhost
        
#logging:
#  level:
#    org.hibernate.SQL: DEBUG

kerubin:
    web:
        allow-origin: ${ALLOW_ORIGIN:http://localhost:4200}
        enable-https: ${ENABLE_HTTPS:false}